"""
14_llm_judge.py — LLM-as-judge evaluation for reply quality.

Judge model : openai/gpt-oss-20b via NVIDIA NIM  (different family from Nemotron
              generator → no self-preference bias).  Falls back to
              meta/llama-3.1-70b-instruct if gpt-oss-20b returns a model-not-found
              error.  Override via JUDGE_MODEL env var.

Generator   : nvidia/nemotron-3-super-120b-a12b  (same pipeline as production)

Rubric (4 dimensions, 1-5 integer scale):
    relevance     — Does the reply address the customer's actual concern?
    empathy       — Does the tone match the customer's emotional state?
    actionability — Is there a clear, specific, executable next step?
    conciseness   — Is the reply appropriately brief (not padded, not too terse)?
    overall       — Overall reply quality (holistic, not an average)
    justification — One-sentence explanation

Judge-vs-human agreement (optional):
    Fill in data/human_judge_ratings.csv (template generated by this script)
    then re-run to see Pearson r, MAE, and ±1-agreement per dimension.

Run:
    $env:NVIDIA_API_KEY='nvapi-...'
    python scripts/14_llm_judge.py [--n 30] [--skip-draft]

    --n          : number of tweets to evaluate (default 30, max 50)
    --skip-draft : skip drafting step; load existing drafts from judge_scores.json

Output:
    results/judge_scores.json
    results/judge_report.txt
    data/human_judge_ratings_template.csv  (fill in human_* columns)
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
from dataclasses import asdict, dataclass, field
from typing import Optional

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))

DATA_DIR    = os.path.join(ROOT, "data")
RESULTS_DIR = os.path.join(ROOT, "results")
GOLDEN_CSV  = os.path.join(DATA_DIR, "golden_labeled.csv")
FALLBACK    = os.path.join(DATA_DIR, "labelled_eval.jsonl")
HUMAN_RAT   = os.path.join(DATA_DIR, "human_judge_ratings.csv")
TEMPL_RAT   = os.path.join(DATA_DIR, "human_judge_ratings_template.csv")
OUT_JSON    = os.path.join(RESULTS_DIR, "judge_scores.json")
OUT_TXT     = os.path.join(RESULTS_DIR, "judge_report.txt")

NIM_BASE_URL     = "https://integrate.api.nvidia.com/v1"
JUDGE_MODEL_PREF = "openai/gpt-oss-20b"        # user-specified
JUDGE_FALLBACK   = "meta/llama-3.1-70b-instruct"
GEN_MODEL        = "nvidia/nemotron-3-super-120b-a12b"

DIMENSIONS = ["relevance", "empathy", "actionability", "conciseness", "overall"]


# ── Data class ────────────────────────────────────────────────────────────

@dataclass
class JudgeScore:
    tweet:         str
    intent:        str
    draft_reply:   str
    grounding_n:   int
    relevance:     Optional[int] = None
    empathy:       Optional[int] = None
    actionability: Optional[int] = None
    conciseness:   Optional[int] = None
    overall:       Optional[int] = None
    justification: str = ""
    judge_model:   str = ""
    judge_error:   Optional[str] = None
    latency_ms:    float = 0.0


# ── NIM client (judge) ────────────────────────────────────────────────────

_judge_client = None
_judge_model_used = None


def get_judge_client():
    global _judge_client, _judge_model_used
    if _judge_client is not None:
        return _judge_client, _judge_model_used

    from openai import OpenAI, NotFoundError, BadRequestError
    try:
        from dotenv import load_dotenv
        load_dotenv()
    except ImportError:
        pass
    key = os.environ.get("NVIDIA_API_KEY", "")
    if not key:
        raise RuntimeError("NVIDIA_API_KEY not set")

    client = OpenAI(base_url=NIM_BASE_URL, api_key=key)
    model  = os.environ.get("JUDGE_MODEL", JUDGE_MODEL_PREF)

    # Probe preferred model
    try:
        client.models.retrieve(model)
        print(f"  Judge model: {model}")
        _judge_client   = client
        _judge_model_used = model
        return client, model
    except Exception as e:
        print(f"  [!]  {model} not available on NIM ({e!s:.60})")
        print(f"  Fallback: {JUDGE_FALLBACK}")
        _judge_client   = client
        _judge_model_used = JUDGE_FALLBACK
        return client, JUDGE_FALLBACK


# ── Judge prompt ──────────────────────────────────────────────────────────

_JUDGE_SYSTEM = (
    "You are an expert evaluator of customer support reply quality. "
    "Score the draft reply on 4 dimensions using integer 1–5 scale:\n"
    "  1=very poor  2=poor  3=acceptable  4=good  5=excellent\n\n"
    "Dimensions:\n"
    "  relevance     — Does the reply address the customer's actual concern?\n"
    "  empathy       — Does the tone match the customer's emotional state?\n"
    "  actionability — Is there a clear, specific, executable next step?\n"
    "  conciseness   — Is the reply appropriately brief? (no padding, not too terse)\n"
    "  overall       — Overall quality (holistic — not an average).\n\n"
    'Output JSON: {"relevance": <1-5>, "empathy": <1-5>, '
    '"actionability": <1-5>, "conciseness": <1-5>, "overall": <1-5>, '
    '"justification": "<one sentence>"}'
)


def _judge_one(tweet: str, intent: str, draft: str) -> dict:
    from openai import RateLimitError, APIStatusError
    client, model = get_judge_client()
    from classifier import _throttle  # shared rate limiter

    user_msg = (
        f"Customer tweet (intent: {intent}):\n{tweet}\n\n"
        f"Draft support reply:\n{draft}"
    )
    for attempt in range(5):
        _throttle()
        try:
            t0 = time.perf_counter()
            resp = client.chat.completions.create(
                model=model,
                temperature=0.0,
                max_tokens=300,
                response_format={"type": "json_object"},
                messages=[
                    {"role": "system", "content": _JUDGE_SYSTEM},
                    {"role": "user",   "content": user_msg},
                ],
            )
            latency_ms = (time.perf_counter() - t0) * 1000
            raw = (resp.choices[0].message.content or "").strip()
            scores = _parse_judge(raw)
            scores["latency_ms"] = latency_ms
            scores["judge_model"] = model
            return scores
        except RateLimitError:
            time.sleep(10 * (attempt + 1))
        except APIStatusError as e:
            if e.status_code in (429, 503):
                time.sleep(15 * (attempt + 1))
            else:
                return {"judge_error": str(e)[:120]}
        except Exception as e:
            return {"judge_error": str(e)[:120]}
    return {"judge_error": "Max retries exceeded"}


def _parse_judge(raw: str) -> dict:
    import re
    import json as _json
    # Try direct parse
    try:
        obj = _json.loads(raw)
    except Exception:
        # Extract JSON block
        m = re.search(r"\{.*\}", raw, re.DOTALL)
        if not m:
            return {"judge_error": f"No JSON in response: {raw[:80]}"}
        try:
            obj = _json.loads(m.group())
        except Exception:
            return {"judge_error": f"Unparseable: {raw[:80]}"}

    result = {}
    for dim in DIMENSIONS:
        v = obj.get(dim)
        if isinstance(v, (int, float)) and 1 <= v <= 5:
            result[dim] = int(round(v))
        else:
            result[dim] = None
    result["justification"] = str(obj.get("justification", "")).strip()
    return result


# ── Draft generation ──────────────────────────────────────────────────────

def run_pipeline(tweets: list[str], labels: list[str]) -> list[dict]:
    """Run classify→retrieve→draft for each tweet. Returns list of dicts."""
    from classifier import classify
    from retrieval import load_index
    from drafter import draft
    idx = load_index(os.path.join(DATA_DIR, "faiss_index.bin"), os.path.join(DATA_DIR, "faiss_meta.jsonl"))
    results = []
    for i, (tweet, label) in enumerate(zip(tweets, labels)):
        print(f"  [{i+1}/{len(tweets)}] Drafting...", end="", flush=True)
        clf = classify(tweet)
        retrieved = idx.query(tweet, top_k=3)
        dr = draft(tweet, clf, retrieved)
        results.append({
            "tweet":       tweet,
            "intent":      label,
            "draft_reply": dr.reply,
            "grounding_n": dr.n_grounding_examples,
            "draft_error": dr.error,
        })
        print(f" {len(dr.reply)} chars  ({'[OK]' if not dr.error else '!'})")
    return results


# ── Human agreement ───────────────────────────────────────────────────────

def compute_human_agreement(judge_scores: list[JudgeScore]) -> Optional[dict]:
    if not os.path.exists(HUMAN_RAT):
        return None

    import pandas as pd
    import numpy as np

    hr = pd.read_csv(HUMAN_RAT)
    # Build tweet → human ratings lookup
    lookup = {}
    for _, row in hr.iterrows():
        key = str(row.get("tweet", ""))[:60]
        lookup[key] = row

    paired_dims = {d: [] for d in DIMENSIONS}
    for js in judge_scores:
        key = js.tweet[:60]
        if key not in lookup:
            continue
        row = lookup[key]
        for dim in DIMENSIONS:
            h_col = f"human_{dim}"
            if h_col in row and not pd.isna(row[h_col]):
                j_val = getattr(js, dim)
                if j_val is not None:
                    try:
                        paired_dims[dim].append((float(row[h_col]), float(j_val)))
                    except (TypeError, ValueError):
                        pass

    if not any(paired_dims.values()):
        return None

    from scipy import stats
    agreement = {}
    for dim, pairs in paired_dims.items():
        if len(pairs) < 5:
            agreement[dim] = {"n": len(pairs), "note": "too few pairs"}
            continue
        human_vals = [p[0] for p in pairs]
        judge_vals = [p[1] for p in pairs]
        r, p_val = stats.pearsonr(human_vals, judge_vals)
        mae = float(np.mean(np.abs(np.array(human_vals) - np.array(judge_vals))))
        within1 = float(np.mean(np.abs(np.array(human_vals) - np.array(judge_vals)) <= 1))
        agreement[dim] = {
            "n":          len(pairs),
            "pearson_r":  round(r, 3),
            "p_value":    round(p_val, 4),
            "mae":        round(mae, 3),
            "within_1":   round(within1, 3),
        }
    return agreement


# ── Report formatting ─────────────────────────────────────────────────────

def format_judge_report(judge_scores: list[JudgeScore],
                         agreement: Optional[dict],
                         judge_model: str) -> str:
    import numpy as np
    lines = []
    lines.append("=" * 72)
    lines.append("LLM-AS-JUDGE EVALUATION REPORT")
    lines.append("=" * 72)
    lines.append(f"Judge model : {judge_model}")
    lines.append(f"Gen model   : {GEN_MODEL}")
    lines.append(f"N evaluated : {len(judge_scores)}")
    lines.append("")

    # Aggregate scores per dimension
    lines.append("─" * 72)
    lines.append("AGGREGATE SCORES  (1=very poor … 5=excellent)")
    lines.append("─" * 72)
    lines.append(f"  {'Dimension':<16s}  {'Mean':>6}  {'Median':>6}  {'Std':>6}  "
                 f"{'≥4 (good+)':>10}")
    lines.append(f"  {'─'*16}  {'─'*6}  {'─'*6}  {'─'*6}  {'─'*10}")
    for dim in DIMENSIONS:
        vals = [getattr(s, dim) for s in judge_scores
                if getattr(s, dim) is not None and not s.judge_error]
        if not vals:
            lines.append(f"  {dim:<16s}  {'N/A':>6}")
            continue
        arr = np.array(vals, dtype=float)
        lines.append(
            f"  {dim:<16s}  {arr.mean():6.2f}  {np.median(arr):6.2f}"
            f"  {arr.std():6.2f}  {np.mean(arr >= 4)*100:8.1f}%"
        )
    lines.append("")

    # Human agreement
    lines.append("─" * 72)
    lines.append("JUDGE vs HUMAN AGREEMENT")
    lines.append("─" * 72)
    if agreement is None:
        lines.append("  Not yet available.  Fill in data/human_judge_ratings.csv")
        lines.append("  (generated template: data/human_judge_ratings_template.csv)")
        lines.append("  then re-run this script.")
    else:
        lines.append(f"  {'Dimension':<16s}  {'N':>4}  {'Pearson r':>9}  {'MAE':>6}  "
                     f"{'±1 agree':>9}")
        lines.append(f"  {'─'*16}  {'─'*4}  {'─'*9}  {'─'*6}  {'─'*9}")
        for dim in DIMENSIONS:
            ag = agreement.get(dim, {})
            if "note" in ag:
                lines.append(f"  {dim:<16s}  {ag['n']:>4}  {ag['note']}")
            else:
                lines.append(
                    f"  {dim:<16s}  {ag.get('n',0):>4}  "
                    f"{ag.get('pearson_r','N/A'):>9}  "
                    f"{ag.get('mae','N/A'):>6}  "
                    f"{ag.get('within_1','N/A'):>9}"
                )
    lines.append("")

    # Per-tweet sample (first 10)
    lines.append("─" * 72)
    lines.append("SAMPLE SCORES (first 10)")
    lines.append("─" * 72)
    for js in judge_scores[:10]:
        err = f"  ⚠ {js.judge_error}" if js.judge_error else ""
        lines.append(f"  [{js.intent}]  {js.tweet[:60]!r}")
        if not js.judge_error:
            scores_str = "  ".join(
                f"{d[0].upper()}:{getattr(js, d)}" for d in DIMENSIONS
            )
            lines.append(f"    Scores: {scores_str}")
            lines.append(f"    Reply : {js.draft_reply[:70]!r}")
            lines.append(f"    Note  : {js.justification[:80]}")
        else:
            lines.append(f"    ⚠ Error: {js.judge_error}")
        lines.append("")

    lines.append("=" * 72)
    return "\n".join(lines)


# ── Main ──────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--n",          type=int, default=30)
    parser.add_argument("--skip-draft", action="store_true",
                        help="Load existing judge_scores.json drafts instead of re-drafting")
    args = parser.parse_args()

    n = min(args.n, 50)

    # ── Load eval tweets ──────────────────────────────────────────────────
    print("Loading evaluation tweets...")
    if os.path.exists(GOLDEN_CSV):
        import pandas as pd
        df = pd.read_csv(GOLDEN_CSV)
        df = df[df["human_label"].notna() & (df["human_label"].str.strip() != "")]
        tweets = df["tweet"].tolist()[:n]
        labels = df["human_label"].str.strip().tolist()[:n]
        print(f"  Source: golden_labeled.csv ({len(tweets)} examples)")
    elif os.path.exists(FALLBACK):
        import json as _json
        rows = [_json.loads(l) for l in open(FALLBACK, encoding="utf-8")][:n]
        tweets = [r["tweet"] for r in rows]
        labels = [r["label"] for r in rows]
        print(f"  Source: labelled_eval.jsonl fallback ({len(tweets)} examples)")
    else:
        raise FileNotFoundError("No evaluation data found")

    # ── Draft replies ──────────────────────────────────────────────────────
    drafts: list[dict] = []
    if args.skip_draft and os.path.exists(OUT_JSON):
        print("Loading existing drafts from judge_scores.json...")
        with open(OUT_JSON, encoding="utf-8") as f:
            existing = json.load(f)
        drafts = existing.get("judge_scores", [])
        # Reconstruct tweet/label order from loaded data
        tweets = [d["tweet"] for d in drafts]
        labels = [d["intent"] for d in drafts]
    else:
        print(f"\nRunning pipeline (classify->retrieve->draft) for {n} tweets...")
        drafts = run_pipeline(tweets, labels)

    # ── Judge each reply ──────────────────────────────────────────────────
    print(f"\nJudging {len(drafts)} replies...")
    judge_scores: list[JudgeScore] = []
    _, judge_model = get_judge_client()

    for i, d in enumerate(drafts):
        reply = d.get("draft_reply", "")
        if not reply or d.get("draft_error"):
            print(f"  [{i+1}/{len(drafts)}] Skipping (no draft reply)")
            js = JudgeScore(
                tweet=d["tweet"], intent=d["intent"],
                draft_reply=reply or "", grounding_n=d.get("grounding_n", 0),
                judge_error=f"No draft: {d.get('draft_error', 'unknown')}"
            )
        else:
            print(f"  [{i+1}/{len(drafts)}] Judging...", end="", flush=True)
            scores = _judge_one(d["tweet"], d["intent"], reply)
            js = JudgeScore(
                tweet=d["tweet"], intent=d["intent"],
                draft_reply=reply, grounding_n=d.get("grounding_n", 0),
                **{k: v for k, v in scores.items()
                   if k in ["relevance", "empathy", "actionability",
                             "conciseness", "overall", "justification",
                             "judge_model", "judge_error", "latency_ms"]},
            )
            if not js.judge_error:
                scores_str = " ".join(
                    f"{d_[0].upper()}:{getattr(js, d_)}" for d_ in DIMENSIONS
                )
                print(f" {scores_str}")
            else:
                print(f" [!] {js.judge_error[:50]}")
        judge_scores.append(js)

    # ── Human agreement ────────────────────────────────────────────────────
    agreement = compute_human_agreement(judge_scores)

    # ── Write human ratings template ───────────────────────────────────────
    import pandas as pd
    tmpl_rows = []
    for js in judge_scores:
        row = {
            "tweet":               js.tweet,
            "intent":              js.intent,
            "draft_reply":         js.draft_reply,
            "judge_overall":       js.overall,
            "human_relevance":     "",
            "human_empathy":       "",
            "human_actionability": "",
            "human_conciseness":   "",
            "human_overall":       "",
        }
        tmpl_rows.append(row)
    tmpl_df = pd.DataFrame(tmpl_rows)
    tmpl_df.to_csv(TEMPL_RAT, index=False)
    print(f"\nHuman ratings template -> {TEMPL_RAT}")

    # ── Save results ───────────────────────────────────────────────────────
    out = {
        "judge_model":  judge_model,
        "gen_model":    GEN_MODEL,
        "n_evaluated":  len(judge_scores),
        "judge_scores": [asdict(js) for js in judge_scores],
        "agreement":    agreement,
    }
    os.makedirs(RESULTS_DIR, exist_ok=True)
    with open(OUT_JSON, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=2)

    report_txt = format_judge_report(judge_scores, agreement, judge_model)
    with open(OUT_TXT, "w", encoding="utf-8") as f:
        f.write(report_txt)

    print()
    print(report_txt)
    print(f"Saved -> {OUT_JSON}")
    print(f"Saved -> {OUT_TXT}")


if __name__ == "__main__":
    main()
